### ISSUE TITLE
[Replicability Stamp] minor error in readme + teaser?

### ISSUE THREAD

**Issue by alecjacobson** [gfxdisp/stelaCSF#1]
Hello, I'm your Replicability Stamp reviewer. This code is well documented and easy to get running.

In the readme, I believe the sample code should be

```
clf;
t_freq = linspace( 0, 60 )'; %Hz, must be a column vector
csf_pars = struct( 's_frequency', 4, 't_frequency', t_freq, 'orientation', 0, 'luminance', 100, 'area', 1, 'eccentricity', 0 );
csf_model = CSF_stelaCSF();
S = csf_model.sensitivity( csf_pars );
plot( t_freq, S );
set( gca, 'YScale', 'log' );
xlabel( 'Temporal frequency [Hz]' );
```

That is, the `csf_model = CSF_stelaCSF();` is needed.

Finally, could you help me reproduce the teaser image?

Running `example_plot_csf.m` produces this image with "Spatial Freq" and "Temporal freq" on the x-y axes. This looks a bit different from the first subimage in the teaser. Am I misreading it?
<img width="547" alt="image" src="https://user-images.githubusercontent.com/2241689/187296815-87704088-21c1-4a21-bf17-24ee1c3750ff.png">

**Comment by alecjacobson** [comment]
btw, if you have scalar data pseudocolored on a `surf`'s vertices (like the height/z-axis in your paper's plots) you can use:

```
surf( s_freq, t_freq, S ,'FaceColor','interp','FaceLighting','phong');
```

This makes it a bit smoother looking.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/2241689/187299037-02a77d0e-bfd6-4214-bee3-406de63ffb79.png">

**Comment by mantiuk** [comment]
Alec, thank you for working on the Replicability Stamp for our paper. 

I have corrected the README.md (thanks for spotting it) and changed the plotting example so the figure should look identical to the teaser in the paper (after rotating the plot). The main difference was that we used a log scale for the figure in the paper.
